/** Registration, login and session for farmers and the administrator. */
const bcrypt = require('bcryptjs');
const { db } = require('../config/db');
const { signToken } = require('../middleware/auth');
const { validate, nextFarmerCode } = require('../utils/helpers');

const publicFarmer = (f) => ({
  id: f.id, farmer_code: f.farmer_code, name: f.name, mobile: f.mobile,
  email: f.email, state: f.state, district: f.district, village: f.village,
  photo: f.photo, created_at: f.created_at, role: 'farmer'
});

exports.register = (req, res) => {
  const { name, mobile, email, password, state, district, village } = req.body;
  const errors = {};

  if (!validate.required(name)) errors.name = 'Enter the farmer name.';
  if (!validate.mobile(mobile)) errors.mobile = 'Enter a valid 10-digit Indian mobile number.';
  if (!validate.email(email)) errors.email = 'Enter a valid email address or leave it blank.';
  if (!validate.password(password)) errors.password = 'Password must be at least 6 characters.';
  if (!validate.required(state)) errors.state = 'Select the state.';
  if (!validate.required(district)) errors.district = 'Enter the district.';
  if (!validate.required(village)) errors.village = 'Enter the village.';

  if (Object.keys(errors).length) return res.status(400).json({ error: 'Please correct the highlighted fields.', errors });

  if (db.prepare('SELECT id FROM farmers WHERE mobile = ?').get(String(mobile).trim())) {
    return res.status(409).json({ error: 'This mobile number is already registered. Try logging in.' });
  }

  // The farmer code is generated by the portal so that farmers never have to
  // type an official identity number into this demo application.
  const code = nextFarmerCode(db);
  const hash = bcrypt.hashSync(String(password), 10);   // passwords are never stored in plain text

  const info = db.prepare(`INSERT INTO farmers (farmer_code,name,mobile,email,password_hash,state,district,village)
    VALUES (?,?,?,?,?,?,?,?)`).run(code, String(name).trim(), String(mobile).trim(),
      email ? String(email).trim() : null, hash, state, district, village);

  db.prepare('INSERT INTO notifications (farmer_id,title,message,type) VALUES (?,?,?,?)')
    .run(info.lastInsertRowid, 'Welcome to the portal',
      `Your farmer ID is ${code}. Upload your documents to start a procurement request.`, 'success');

  const farmer = db.prepare('SELECT * FROM farmers WHERE id = ?').get(info.lastInsertRowid);
  const token = signToken({ id: farmer.id, role: 'farmer', name: farmer.name });
  res.status(201).json({ token, user: publicFarmer(farmer) });
};

exports.login = (req, res) => {
  const { loginId, password } = req.body;
  if (!validate.required(loginId) || !validate.required(password)) {
    return res.status(400).json({ error: 'Enter your mobile number (or email) and password.' });
  }
  const id = String(loginId).trim();
  const farmer = db.prepare('SELECT * FROM farmers WHERE mobile = ? OR email = ?').get(id, id);
  if (!farmer || !bcrypt.compareSync(String(password), farmer.password_hash)) {
    return res.status(401).json({ error: 'Mobile number or password is incorrect.' });
  }
  const token = signToken({ id: farmer.id, role: 'farmer', name: farmer.name });
  res.json({ token, user: publicFarmer(farmer) });
};

exports.adminLogin = (req, res) => {
  const { username, password } = req.body;
  const admin = db.prepare('SELECT * FROM admins WHERE username = ?').get(String(username || '').trim());
  if (!admin || !bcrypt.compareSync(String(password || ''), admin.password_hash)) {
    return res.status(401).json({ error: 'Administrator username or password is incorrect.' });
  }
  const token = signToken({ id: admin.id, role: 'admin', name: admin.name });
  res.json({ token, user: { id: admin.id, name: admin.name, username: admin.username, role: 'admin' } });
};

exports.me = (req, res) => {
  if (req.user.role === 'admin') {
    const a = db.prepare('SELECT id,name,username FROM admins WHERE id = ?').get(req.user.id);
    return res.json({ user: { ...a, role: 'admin' } });
  }
  const f = db.prepare('SELECT * FROM farmers WHERE id = ?').get(req.user.id);
  if (!f) return res.status(404).json({ error: 'Account not found.' });
  res.json({ user: publicFarmer(f) });
};

/**
 * Forgot password - DEMO ONLY.
 * A real portal would send a one-time password by SMS. Here we simply confirm
 * that the number exists and let the farmer set a new password immediately,
 * so that the flow can be demonstrated offline.
 */
exports.resetPassword = (req, res) => {
  const { mobile, newPassword } = req.body;
  if (!validate.mobile(mobile)) return res.status(400).json({ error: 'Enter a valid 10-digit mobile number.' });
  if (!validate.password(newPassword)) return res.status(400).json({ error: 'New password must be at least 6 characters.' });

  const farmer = db.prepare('SELECT id FROM farmers WHERE mobile = ?').get(String(mobile).trim());
  if (!farmer) return res.status(404).json({ error: 'No account is registered with this mobile number.' });

  db.prepare('UPDATE farmers SET password_hash = ? WHERE id = ?')
    .run(bcrypt.hashSync(String(newPassword), 10), farmer.id);
  res.json({ message: 'Password changed. You can log in with the new password now.' });
};

exports.publicFarmer = publicFarmer;
